["text", "category"]
["showRandomQuote", "random", "innerHTML"]
["fetchQuotesFromServer", "function"]
["populateCategories", "categoryFilter", "document.getElementById", "appendChild", "map"]
["localStorage.setItem"]
["Math.random"]
["localStorage.getItem"]
["option", "value", "textContent"]
["await", "async", "https://jsonplaceholder.typicode.com/posts", ".json"]
["createAddQuoteForm"]
["addEventListener"]
["filterQuote", "quoteDisplay"]
["method", "POST", "JSON.stringify", "headers", "application/json", "Content-Type"]
["createElement"]
["Export Quotes"]
["selectedCategory"]
["syncQuotes"]